In [1]:
import numpy as np

# Activation function (Step function)
def activation_function(x):
    res =  np.maximum(0,x)

    if res > 0.5:
        return 1
    else:
        return 0

# Perceptron training function
def train_perceptron(data, labels, epochs=10, learning_rate=0.05):
    # Initialize weights and bias to zeros
    weights = np.zeros(data.shape[1])   # 1 x 2 array
    bias = 0.0
    
    for epoch in range(epochs):
        for i in range(len(data)):
            x = data[i]     # makes it a 1 x 2 array
            y = labels[i]
            
            # Calculate the weighted sum
            weighted_sum = np.dot(weights, x) + bias
            
            # Pass through activation function
            prediction = activation_function(weighted_sum)
            
            # Update weights and bias
            error = y - prediction
            weights += learning_rate * error * x
            bias += learning_rate * error
            
    return weights, bias

# Main function
if __name__ == "__main__":
    # Define training data for AND gate
    # x1, x2 are inputs and y is output
    training_data = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                              [0, 0, 0, 0, 0, 0, 0, 1, 4, 0],
                              [0, 0, 0, 0, 0, 0, 0, 1, 4, 0],
                              [0, 0, 0, 0, 0, 0, 0, 1, 4, 0],
                              [0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
                              [0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
                              [0, 0, 0, 0, 0, 0, 0, 3, 0, 0],
                              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                              [0, 0, 0, 7, 0, 0, 0, 0, 0, 0],
                              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
    print(training_data)
    # 4 x 2 array

    labels = np.array([0, 1, 1, 1, 0, 0, 0, 0, 0, 0])  # Output for AND gate  # 1 x 4 array

    # Train the perceptron
    weights, bias = train_perceptron(training_data, labels, epochs=10, learning_rate=0.1)
    
    print("Trained weights:", weights)
    print("Trained bias:", bias)

    # Test the perceptron
    test_data = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    test_result = activation_function(np.dot(weights, test_data) + bias)
    print(f"\nPrediction for [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]: {test_result}")

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 4 0]
 [0 0 0 0 0 0 0 1 4 0]
 [0 0 0 0 0 0 0 1 4 0]
 [0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 7 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Trained weights: [0.  0.  0.  0.  0.  0.  0.  0.1 0.4 0. ]
Trained bias: 0.1

Prediction for [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]: 0
